[package]
name = "captee-platform"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Captee filesystem, compiler, capture, and Linux adapters"

[dependencies]
ashpd.workspace = true
async-io.workspace = true
captee-core = { version = "0.1.0", path = "../captee-core" }
futures-util.workspace = true
png.workspace = true
serde_json.workspace = true
url.workspace = true

[lints]
workspace = true
